# NOTE: This file is generated by build_app_uninstall.sql.
exec drop_sequence('seq_example_id');
exec drop_table('starter_pack_example');
exec drop_view('starter_pack_example_v');
exec drop_package('saas_app');
exec drop_package('saas_app_admin');
exec drop_procedure('on_create_account');
exec drop_procedure('on_delete_account');
exec drop_procedure('on_login');
