-- NOTE: This file is generated by build_app_uninstall.sql.
exec drop_package('saas_app_config');
exec drop_package('saas_app');
exec drop_package('saas_app_admin');
exec drop_procedure('on_create_account');
exec drop_procedure('on_delete_account');
exec drop_procedure('on_login');
