-- NOTE: This file is generated by build_app_uninstall.sql.
drop package saas_auth_config;
drop table saas_auth_role cascade constraints purge;
drop table saas_auth cascade constraints purge;
exec drop_view('v_saas_auth_available_accounts');
drop table flash_message cascade constraints purge;
drop package saas_auth_pkg;
exec drop_procedure('on_create_account');
exec drop_procedure('on_delete_account');
exec drop_procedure('on_login');
drop view user_flash_message;
