
create or replace package saas_auth_config as 

   -- Determines if http or https for links generated by the auth service.
   saas_auth_protocol varchar2(12) := 'https';

   -- The domain used in links generated by the auth service.
   saas_auth_domain varchar2(120) := 'superloser.io';

   -- From address to use in generated emails.
   saas_auth_from_address varchar2(120) := 'ethan@arclogicsoftware.com';

   saas_auth_salt varchar2(120) := 'Another great cup of coffee brought to you by Gabs!';
   saas_auth_test_pass varchar2(120) := 'superPPP$$$';
   saas_auth_pass_prefix varchar2(120) := 'PPP';

   -- Limits the rate of auth requests within any 10 minute window.
   -- Null to disable.
   auth_request_rate_limit number := 1000;

   -- How long is a new token good for?
   -- Null or 0 makes the limit unlimited.
   token_good_for_minutes number := 60*24;

   -- User will not be allowed to login if email is not verified.
   -- Null to disable
   allowed_logins_before_email_verification_is_required number := 1;

   -- Enable auth notifications if your pages use them.
   flash_notifications boolean := true;

   password_reset_token_good_for_minutes number := 15;

   send_all_emails_to varchar2(120) := 'post.ethan@gmail.com';

end;
/
